#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# Inventory Generator
# ─────────────────────────────────────────────────────────
# Reads Terraform outputs and generates an Ansible inventory
# file (inventory.ini) with the EC2 instance IP and SSH key.
#
# Usage: ./generate-inventory.sh
# ─────────────────────────────────────────────────────────

set -euo pipefail

TERRAFORM_DIR="../terraform"
INVENTORY_FILE="inventory.ini"
KEY_FILE="platform-key.pem"

echo "Retrieving Terraform outputs..."

SERVER_IP=$(terraform -chdir="$TERRAFORM_DIR" output -raw server_public_ip)
terraform -chdir="$TERRAFORM_DIR" output -raw private_key_pem > "$KEY_FILE"
chmod 400 "$KEY_FILE"

cat > "$INVENTORY_FILE" <<EOF
# ─────────────────────────────────────────────────────────
# Ansible Inventory — Auto-generated
# ─────────────────────────────────────────────────────────
# Generated by generate-inventory.sh from Terraform outputs.
# Do not edit manually; re-run the script to update.
# ─────────────────────────────────────────────────────────

[app_servers]
${SERVER_IP} ansible_ssh_private_key_file=${KEY_FILE}
EOF

echo "Inventory generated: ${INVENTORY_FILE}"
echo "Server IP: ${SERVER_IP}"
