# API Configuration
api:
  replicas: 2
  image:
    repository: ghcr.io/carlosfcruz/devopsproject
    tag: eb4e0746c0bf736aaa05ff33a725160c6d8707bf
  port: 8000
  env:
    APP_NAME: "platform"
    APP_ENV: "staging"
    LOG_LEVEL: "info"
    POSTGRES_HOST: "postgres"
    REDIS_HOST: "redis"

# PostgreSQL Configuration
postgres:
  image: postgres:16
  port: 5432
  storage: 1Gi

# Redis Configuration
redis:
  image: redis:7
  port: 6379

# Ingress Configuration
ingress:
  enabled: true
  host: platform.local
  className: nginx

# Secret reference
secret:
  name: db-credentials
